version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test_password
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_advertised__address=:7474
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/data:/data
