apiVersion: v1
kind: Service
metadata:
  name: maple-architecture-neo4j-service
  namespace: maple-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  selector:
    app: maple-architecture-neo4j
