apiVersion: apps/v1
kind: Deployment
metadata:
  name: maple-architecture-deployment
  namespace: maple-system
  labels:
    app: maple-architecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maple-architecture
  template:
    metadata:
      labels:
        app: maple-architecture
    spec:
      containers:
        - name: maple-architecture-container
          image: shobhittyagi1011/maple-architecture-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: DB_URI
              value: neo4j://maple-architecture-neo4j-service:7687
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: maple-architecture-secrets
                  key: NEO4J_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: maple-architecture-secrets
                  key: NEO4J_PASSWORD

        - name: envoy
          image: envoyproxy/envoy:v1.27.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9901
            - containerPort: 8081
          volumeMounts:
            - name: maple-architecture-envoy-config
              mountPath: /etc/envoy
          args:
            - "--config-path"
            - "/etc/envoy/envoy.yaml"

      volumes:
        - name: maple-architecture-envoy-config
          configMap:
            name: maple-architecture-envoy-config
