apiVersion: v1
kind: Service
metadata:
  name: maple-architecture-service
  namespace: maple-system
  labels:
    app: maple-architecture
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: admin
      port: 9901
      targetPort: 9901
    - name: envoy
      port: 8081
      targetPort: 8081
  selector:
    app: maple-architecture